### ISSUE TITLE
都发往从库了～

### ISSUE THREAD

**Issue by i36lib** [Qihoo360/Atlas#107]
Hi， 我们在生产环境部署了两台Atlas，后端一台主三台从，但是发现Atlas并没有将请求转发，用MySQL Workbench查看，发现大量的读还是发往主库了。配置是按照你们的文档来配置的，应用层我们用的是Python/Flask，请问这会是什么原因导致Atlas不走从库？

**Comment by yihaoDeng** [comment]
看一下Python/Flask对sql的处理方法，比如事务等确实需要是发到主库上的！

**Comment by i36lib** [comment]
的确，设置了autocommit=false，然后每句sql都开启了一个事务，全跑主库了。。。
