### ISSUE TITLE
需要怎么配置，才能让主实例也能分担一些SQL读请求？

### ISSUE THREAD

**Issue by kingkasuo** [Qihoo360/Atlas#122]
读写分离后，所有读操作都到“读实例”上了。而“主实例” 完全没有读请求过来，需要怎么配置，才能让主实例也能分担一些SQL读请求？

**Comment by zhuchao-hit** [comment]
把主库的IP和端口也写到read-only那个配置项里。

**Comment by kingkasuo** [comment]
了解了，多谢。
