### ISSUE TITLE
请问怎么查看才能知道ATLAS已经把查询转发到从库了？

### ISSUE THREAD

**Issue by chujian** [Qihoo360/Atlas#148]
ATLAS有转发的日志嘛？还是通过什么其他途径查看。

**Comment by glaciert1029** [comment]
有

**Comment by dragonv9** [comment]
http://www.cnblogs.com/yyhh/archive/2015/12/29/5084844.html,推荐你看下这下面的测试工具使用，

**Comment by caozhaoliang** [comment]
你也可以在几个从库上使用tcpdump 抓包查看。。
