### ISSUE TITLE
Ubuntu 启动报错 cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by javastar920905** [Qihoo360/Atlas#167]
使用的版本版本 2.2 
https://github.com/Qihoo360/Atlas/releases/download/2.2/Atlas-2.2-debian6.0-x86_64.deb
安装 sudo dpkg -i Atlas-2.2-debian7.0-x86_64.deb 
操作过程 :
sudo vim test.cnf   调整了master 的ip和端口  
启动
/usr/local/mysql-proxy$ sudo ./bin/mysql-proxyd test start

报错如下:
/usr/local/mysql-proxy/bin/mysql-proxy: error while loading shared libraries: libcrypto.so.0.9.8: cannot open shared object file: No such file or directory
error: failed to start MySQL-Proxy of test

还有个问题  我该怎么卸载...新手

**Comment by newboy2004** [comment]
少 libcrypto.so.0.9.8 这个库   你是什么linux  如果是centos 就 yum providers */libcrypto.so.0.9.8 搜一下 然后 yum install一下 在重新启动就好了



newboy2004@126.com
 
发件人： 徒手游
发送时间： 2017-12-12 19:17
收件人： Qihoo360/Atlas
抄送： Subscribed
主题： [Qihoo360/Atlas] Ubuntu 启动报错 cannot open shared object file: No such file or directory (#167)
使用的版本版本 2.2
https://github.com/Qihoo360/Atlas/releases/download/2.2/Atlas-2.2-debian6.0-x86_64.deb
安装 sudo dpkg -i Atlas-2.2-debian7.0-x86_64.deb
操作过程 :
sudo vim test.cnf 调整了master 的ip和端口
启动
/usr/local/mysql-proxy$ sudo ./bin/mysql-proxyd test start
报错如下:
/usr/local/mysql-proxy/bin/mysql-proxy: error while loading shared libraries: libcrypto.so.0.9.8: cannot open shared object file: No such file or directory
error: failed to start MySQL-Proxy of test
还有个问题 我该怎么卸载...新手

**Comment by javastar920905** [comment]
Ubuntu 启动报错, 是ubuntu 版本的哦,先谢啦 最近没弄这一块了 后期有空再跟进一下吧
