### ISSUE TITLE
问题反馈没人管，发邮件也没人回，哎，失望。换一个中间件

### ISSUE THREAD

**Issue by ShadowDead** [Qihoo360/Atlas#169]

**Comment by DavidLiuXh** [comment]
我们目前的精力放在旧版本的重构和新功能的开发上.
年底事情都比较多, 我们多半会优先处理公司内部的事情.请您谅解.

您的问题, 我们这边并没有重现, 目前找起来比较困难. 带来不便, 十分抱歉~~
邮件今早已回复.

**Comment by lazio579** [comment]
换我们网易的吧，https://github.com/Lede-Inc/cetus 
保证积极回复和解决
