### ISSUE TITLE
master的数据与slave的是一致的吗？

### ISSUE THREAD

**Issue by windflowerly** [Qihoo360/Atlas#175]
非sharding版的主从同步的策略什么样的？

比如：我建立了一个1主三从的集群。插入了100条数据。那么这100条是均匀的分布在三个slave中，还是master与各个slave各有一套完整的数据。

**Comment by yihaoDeng** [comment]
Atlas 不负责主从同步，DBA自己搞。 




在 2018-03-15 16:28:57，"windflowerly" <notifications@github.com> 写道：


非sharding版的主从同步的策略什么样的？

比如：我建立了一个1主三从的集群。插入了100条数据。那么这100条是均匀的分布在三个slave中，还是master与各个slave各有一套完整的数据。

**Comment by windflowerly** [comment]
没明白“Atlas 不负责主从同步”，这句话啥意思？

**Comment by vectormail** [comment]
binlog去做主从，明白不？
