### ISSUE TITLE
That had some errors in Mac Air compiled the Atlas from source code 

### ISSUE THREAD

**Issue by yuchao86** [Qihoo360/Atlas#19]
My computer information is:
┌─[yuchao@localhost] - [~/Github/Atlas] - [2014-09-30 01:10:54]
└─[0] <git:(master 102f9f✱✈) > uname -a
Darwin localhost 13.4.0 Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64 x86_64
when I make the Atlas,
It is some errors:
libtool: link: gcc -dynamiclib  -o .libs/libmysql-chassis.0.dylib  .libs/libmysql_chassis_la-lua-load-factory.o .libs/libmysql_chassis_la-lua-scope.o .libs/libmysql_chassis_la-chassis-plugin.o .libs/libmysql_chassis_la-chassis-log.o .libs/libmysql_chassis_la-chassis-mainloop.o .libs/libmysql_chassis_la-chassis-event-thread.o .libs/libmysql_chassis_la-chassis-keyfile.o .libs/libmysql_chassis_la-chassis-path.o .libs/libmysql_chassis_la-chassis-filemode.o .libs/libmysql_chassis_la-chassis-limits.o .libs/libmysql_chassis_la-chassis-shutdown-hooks.o .libs/libmysql_chassis_la-chassis-stats.o .libs/libmysql_chassis_la-chassis-frontend.o .libs/libmysql_chassis_la-chassis-options.o .libs/libmysql_chassis_la-chassis-unix-daemon.o .libs/libmysql_chassis_la-chassis-win32-service.o   /usr/local/lib/libevent.dylib -L/usr/local/Cellar/glib/2.40.0_1/lib -L/usr/local/opt/gettext/lib -L/usr/local/lib -llua -lgmodule-2.0 -lgthread-2.0 ./.libs/libmysql-chassis-timing.dylib /Users/yuchao/Github/Atlas/src/.libs/libmysql-chassis-glibext.dylib ./.libs/libmysql-chassis-glibext.dylib -lm -ldl -lcrypto -ljemalloc -lglib-2.0 -lintl  -Wl,-dylib_file -Wl,/usr/local/mysql-proxy/lib/libmysql-chassis-glibext.0.dylib:/Users/yuchao/Github/Atlas/src/.libs/libmysql-chassis-glibext.dylib   -install_name  /usr/local/mysql-proxy/lib/libmysql-chassis.0.dylib -compatibility_version 1 -current_version 1.0 -Wl,-single_module
Undefined symbols for architecture x86_64:
  "_network_backends_free", referenced from:
      _chassis_free in libmysql_chassis_la-chassis-mainloop.o
  "_network_mysqld_con_free", referenced from:
      _chassis_event_thread_free in libmysql_chassis_la-chassis-event-thread.o
  "_network_mysqld_con_handle", referenced from:
      _chassis_event_handle in libmysql_chassis_la-chassis-event-thread.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: **\* [libmysql-chassis.la] Error 1
make[2]: **\* [all] Error 2
make[1]: **\* [all-recursive] Error 1
make: **\* [all] Error 2

how to solu the error?

**Comment by scofier** [comment]
我直接mac 安装，提示

./network-socket.h:39:10: fatal error: 'linux/version.h' file not found
