### ISSUE TITLE
SQL查询语句连Atlas偶现与连数据库获取结果不一致现象

### ISSUE THREAD

**Issue by Martin404** [Qihoo360/Atlas#74]
java web项目，spring+mybatis，数据库连接池druid，最近遇到个诡异的问题，偶尔出现，现象是同一个sql查询语句，直连mysql数据库获取的记录条数跟连atlas获取记录条数不一样，sql语句改成/**master**/直接从主库查就正常了，特来寻求大神解答

**Comment by zjulbj** [comment]
从库的数据不同步吧，不加/*master*/默认是从从库查的，看看从库数据是不是最新

**Comment by Martin404** [comment]
主从数据是一致的，直接查主库或者从库记录返回list是正常的，连proxy查数据库返回list第一条记录

**Comment by longxibendi** [comment]
把你的建表语句，sql语句，写出来啊

**Comment by Martin404** [comment]
已找到原因 非Atlas问题

**Comment by wangbing99** [comment]
也碰到这个问题了，去掉my sql proxy后就正常了，希望能知道到底为什么。。。
